### ISSUE TITLE
Error in latest version.

### ISSUE THREAD

**Issue by deide6102** [BoBkiNN/ClickHarvest#3]
[9:49:00 AM ERROR] [Minecraft] Could not pass event PlayerInteractEvent to ClickHarvest v1.2-b19-R

Issues is occurring on line 38 of the ClickHarvest class. It is saying that you "Cannot drop air".

I assume this has to do when you try and drop 0 of an item?
I can provide full error stack if needed. It isn't causing any usability issues, just very messy in my logs.

**Comment by BoBkiNN** [comment]
Thanks for bug report, can you provide steps to reproduce this bug?

**Comment by deide6102** [comment]
> Thanks for bug report, can you provide steps to reproduce this bug?

It happens when right click harvesting wheat. It isn't every block you harvest, but it happens a lot when doing large fields.

I will say I am running a 1.20.1 spigot server.

**Comment by BoBkiNN** [comment]
ok i will check it when i have time

**Comment by deide6102** [comment]
Thank you! Like I said, it isn't game breaking, just fills up the console. I am unsure of if it prevents wheat drops or not when it occurs, like I said I believe it occurs when seed drop hits 0.

**Comment by BoBkiNN** [comment]
Must be fixed in 1.3
